name: osm_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: '>=2.19.6 <3.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.55.1
  pointer_interceptor: ^0.9.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locations/